name: Build Release

on:
  push:
    branches:
      - main

jobs:
  build_package:
    uses: bitcompat/base/.github/workflows/build.yaml@main
    with:
      name: main
      version: 1.0.3 # renovate: datasource=github-releases depName=bitnami/render-template
      latest: true
      major_only_tag: true
    secrets: inherit
