name: Build

on:
  push:
    branches-ignore:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  build_package:
    if: github.event_name != 'pull_request_target' || github.repository_owner != 'bitcompat'
    uses: bitcompat/base/.github/workflows/build.yaml@main
    with:
      name: main
      push: false
      version: ''
      latest: true
    secrets: inherit
